### ISSUE TITLE
Minor Suggestion: Clickable cards option to open card links to gamepedia

### ISSUE THREAD

**Issue by justingolden21** [mrzealot/deckdiff#1]
I just stumbled upon this awesome extension on the reddit thread from 2 years ago (can't believe it's only got 1 star). Anyway, I love the extension, but I think it would be awesome if there was an option to click the cards to open a new tab with the card, for players who don't know what all the cards do, it would make googling faster.

I'm down to implement it and create a PR if that's ok with you.

Thank you.

**Comment by mrzealot** [comment]
Howdy! Thanks for the kind words! And sure, that was on the agenda originally, but I couldn't perform a definite mapping from the card IDs to a webpage/image, iirc. Don't know how things have changed since then, maybe it's possible now. But even if it isn't, some heuristic could do fine as well.

A PR is more than welcome, btw. If you can manage to map to a direct image, I'd suggest going for a popup tooltip, with the new tab webpage as a backup...

**Comment by justingolden21** [comment]
Thanks for the quick reply. That's a good idea. I'll look into that sometime. Glad to hear that a PR would be welcome before I start; always good to confirm.

**Comment by justingolden21** [comment]
Just created the pull request: https://github.com/mrzealot/deckdiff/pull/2
